#!/bin/bash 

#while inotifywait -r -qq .
while sleep .1
do
  if ! make -q;
  then
    beep
    clear
    make 2>&1 | head -n `tput lines`
    if [ ${PIPESTATUS[0]} = '0' ]
    then
      play -q ding.wav &> /dev/null &
    else
      play -q error.wav &> /dev/null &
    fi
  fi
done
